# render.yaml

services:
  - name: web
    type: web
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        value: postgresql://postgres:Eyeoftiger123@<HOSTNAME>:5432/dashboard # Reemplaza <HOSTNAME> con el host de tu base de datos de Render
    plan: starter
    autoscaling:
      minInstances: 1
      maxInstances: 3
    healthCheckPath: /
