# render.yaml

services:
  - name: web
    type: web
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        value: postgresql://dashboard_17mu_user:D22NUvfidtxpb0CkR4trowD0n5qQJJQJ@dpg-csr764t2ng1s73f6mu90-a/dashboard_17mu # Reemplaza <HOSTNAME> con el host de tu base de datos de Render
    plan: starter
    autoscaling:
      minInstances: 1
      maxInstances: 3
    healthCheckPath: /
